import = [
  "~/.config/alacritty/keybindings.toml",
  "~/.config/alacritty/rose-pine.toml",
]

live_config_reload = true

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 17

[font.offset]
y = 3

[font.glyph_offset]
y = 3

[window]
startup_mode = "Windowed" # Maximized, Fullscreen, Windowed
decorations = "None" # Full, None
dimensions = { columns = 150, lines = 40}
position = {x =220, y = 55}
dynamic_padding =false
opacity = 0.90

[mouse]
hide_when_typing = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "Never"

[env]
TERM = "alacritty"

[scrolling]
history = 2000
