# dotfiles
alias dt='cd ~/.dotfiles && nvim .'

# alacritty
alias ala='alacritty'
alias ac='nvim "$HOME/.config/alacritty/alacritty.toml"'   #open alacritty config
alias ak='nvim "$HOME/.config/alacritty/keybindings.toml"' #open alacritty keybindings

# neovim
alias v='nvim .'
alias vv='nvim'
alias nc='cd ~/.config/nvim/ && nvim .'                              #open neovim config
alias color='nvim ~/.config/nvim/lua/ekodes/plugins/colorscheme.lua' #change neovim colorscheme

# bash
alias ali='nvim .bash_aliases'  #open bash shortcuts
alias ar='source .bash_aliases' #refresh bash shortcuts
alias bsh='nvim ~/.bashrc'      #open bash
alias br='source ~/.bashrc'     #refresh bash
alias st='startx'
alias g='bash ~/pomo.sh'

# xmodmap
alias xr='xmodmap ~/.Xmodmap'

# leet
alias leet='cd ~/leet && nvim .'

# eza
alias lsa='eza -la'
alias l='eza'

# themes
alias rt='bash ~/.config/script/rose-pine-theme.sh && br'
alias gt='bash ~/.config/script/gruvbox-theme.sh && br'

# tmux
alias tm='tmux'
alias tc='nvim ~/.tmux.conf'             #open tmux config
alias ts='nvim ~/.tmux_startup.sh'       #open script
alias tr='tmux source-file ~/.tmux.conf' #refresh tmux config
alias tk='tm kill-session'               #tmux kill-session
alias ta='tm a'                          #attach to tmux session
alias tl='tm ls'                         #list tmux sessions

# terminal
alias update='sudo apt update'
alias upgrade='sudo apt upgrade'
alias inst='sudo apt install'
alias purge='sudo apt purge'
alias armv='sudo apt autoremove'
alias h='cd ~'
alias c='clear'
alias e='exit'

# git
alias gs='git status'
alias ga='git add'
alias gc='git commit -m'
alias gca='git commit --amend --no-edit'
alias gp='git push'
alias gpl='git pull'
alias gco='git checkout'
alias gb='git branch'
alias gcm='git checkout main'
alias gl='git log'
alias glog='git log --oneline --graph --decorate'
alias gd='git diff'
alias gh-create='gh repo create --private --source=. --remote=origin && git push -u --all && gh browse'
alias gcount='git rev-list --count HEAD'

# npm
alias build='npm run build'   # Shortcut for npm build
alias dev='npm run dev'       # Shortcut for npm dev
alias lint='npm run lint'     # Shortcut for npm lint
alias deploy='npm run deploy' # Shortcut for npm deploy
alias install='npm install'   # Install dependencies
alias nu='npm update'         # Update dependencies
alias nug='npm update -g'     # Update global dependencies
alias np='npm publish'        # Publish package

# changing directory
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'
