unbind C-b
unbind (
unbind )
set -g prefix C-f  # Set new prefix to Ctrl + f

# Create new window using Ctrl + n
bind-key -n C-n new-window

# Split window horizontally with Ctrl + t
bind-key -n C-t split-window -h
bind-key -n C-r split-window -v

set -g base-index 1  # Start window numbering from 1
set -g pane-base-index 1  # Start pane numbering from 1
setw -g pane-base-index 1  # Apply to all windows

set -sg escape-time 1
set -g mouse on
set -ga terminal-overrides ',*:Tc'
# List of plugins

# Set tmux theme
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main' # Options are 'main', 'moon' or 'dawn'

# tmux theme
set -g @plugin 'tmux-plugins/tpm'
# To update plugin for future revisions or bug fixes, do the "Prefix + U" keycombo

# Initialize TPM (keep this line at the bottom)
run '~/.tmux/plugins/tpm/tpm'
